# Generated by Django 5.1.2 on 2025-12-01 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="URL slug (e.g., 'home', 'about')", unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('statistics', 'Statistics Section'), ('credibility', 'Credibility Section'), ('testimonials', 'Testimonials Section'), ('pain_points', 'Pain Points & Solutions Section'), ('what_makes_me_different', 'What Makes Me Different Section'), ('featured_publications', 'Featured Publications Section'), ('services', 'Services Section'), ('meet_kim', 'Meet Kim Herrlein Section'), ('mission', 'Mission Section'), ('free_resource', 'Free Resource Section'), ('footer', 'Footer Section')], max_length=50)),
                ('internal_label', models.CharField(help_text="Internal label for identification (e.g., 'Homepage Hero v1')", max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('section_config', models.JSONField(default=dict, help_text='Section configuration matching Backend Config Blueprint')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='myApp.page')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'unique_together': {('page', 'sort_order')},
            },
        ),
    ]
