# Generated by Django 5.1.2 on 2025-12-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_page_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='draft_config',
            field=models.JSONField(blank=True, default=dict, help_text='Draft configuration (what user is editing)'),
        ),
        migrations.AddField(
            model_name='section',
            name='published_config',
            field=models.JSONField(blank=True, default=dict, help_text='Published configuration (what public site shows)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_config',
            field=models.JSONField(blank=True, default=dict, help_text='DEPRECATED: Use published_config. Kept for backward compatibility.'),
        ),
    ]
