# Generated by Django 5.1.2 on 2025-12-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_section_draft_config_section_published_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('secure_url', models.URLField(max_length=500)),
                ('web_url', models.URLField(max_length=500)),
                ('thumb_url', models.URLField(max_length=500)),
                ('bytes_size', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('format', models.CharField(max_length=10)),
                ('tags_csv', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='myApp_media_created_fdba2e_idx'), models.Index(fields=['is_active', '-created_at'], name='myApp_media_is_acti_fb35f7_idx')],
            },
        ),
    ]
